# -*- coding: utf-8 -*-
"""Farzaneh_DV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBgwPTeveh5KM7NB9aEFbtYwaoa0BEou
"""

# Data Analyst Jobs Visualization Script

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
from wordcloud import WordCloud

data = pd.read_csv('/content/DataAnalyst.csv')
data.head(3)

# Drop the unnamed column if it exists
if 'Unnamed: 0' in data.columns:
    data.drop(['Unnamed: 0'], axis=1, inplace=True)

# Replace placeholder values (-1, -1.0, '-1') with NaN
data.replace([-1, -1.0, '-1'], np.nan, inplace=True)

data.info()  # Check the structure of the dataset after initial cleaning

# Clean 'Company Name' column
if 'Company Name' in data.columns:
    data['Company Name'] = data['Company Name'].astype(str)
    data[['Company Name', '_']] = data['Company Name'].str.split('\n', n=1, expand=True)

# Split 'Job Title' into title and department
data[['Job Title', 'Department']] = data['Job Title'].str.split(',', n=1, expand=True)

data.head(3)  # Verify the changes

# Replace invalid salary entries (-1) with NaN
data['Salary Estimate'] = data['Salary Estimate'].replace('-1', None)

# Extract salary ranges (e.g., "$37K-$66K") and remove Glassdoor suffix
data['Salary Estimate'] = data['Salary Estimate'].str.extract(r'(\$\d+K-\$\d+K)')[0]

# Drop rows with missing salary estimates
data = data.dropna(subset=['Salary Estimate'])

# Clean salary data and split into Min_Salary and Max_Salary
data[['Min_Salary', 'Max_Salary']] = (
    data['Salary Estimate']
    .str.replace('K', '', regex=False)
    .str.replace('$', '', regex=False)
    .str.split('-', expand=True)
)

# Convert Min_Salary and Max_Salary to numeric values
data['Min_Salary'] = pd.to_numeric(data['Min_Salary'], errors='coerce') * 1000
data['Max_Salary'] = pd.to_numeric(data['Max_Salary'], errors='coerce') * 1000

# Drop rows where salary conversion failed
data = data.dropna(subset=['Min_Salary', 'Max_Salary'])

# Ensure Min_Salary and Max_Salary columns exist for future code cells
data['Min_Salary'] = data['Min_Salary'].astype(float)
data['Max_Salary'] = data['Max_Salary'].astype(float)

# Drop the original 'Salary Estimate' column as it is no longer needed
data = data.drop(columns=['Salary Estimate'])

data[['Min_Salary', 'Max_Salary']].head()  # Verify the cleaned salary columns

# Function to check missing values
def missing_values_table(df):
    missing_values = df.isnull().sum()
    missing_percentage = 100 * (missing_values / len(df))
    return pd.DataFrame({
        'Missing Values': missing_values,
        '% of Total Values': missing_percentage
    }).sort_values(by='Missing Values', ascending=False)

# Display missing values summary
print("Missing Values Summary (Before Cleaning):")
print(missing_values_table(data))

# Drop columns with excessive missing data
columns_to_drop = ['Competitors']  # Dropped due to 76% missing values
data.drop(columns=[col for col in columns_to_drop if col in data.columns], inplace=True)

# Standardize and clean the 'Easy Apply' column
if 'Easy Apply' in data.columns:
    data['Easy Apply'] = data['Easy Apply'].replace({'True': True, 'False': False}).fillna(False).astype(int)

# Remove rows with missing or 'Unknown' values in visualization-critical columns
visualization_critical_columns = [
    'Industry', 'Sector', 'Size', 'Rating', 'Min_Salary', 'Max_Salary', 'Location', 'Job Title', 'Revenue', 'Founded'
]
for col in visualization_critical_columns:
    if col in data.columns:
        data = data[~data[col].isnull()]  # Drop rows with nulls
        data = data[data[col] != 'Unknown']  # Drop rows labeled as 'Unknown'

# Fill missing values for non-visualization-critical columns
if 'Department' in data.columns:
    data['Department'] = data['Department'].fillna('N/A')  # Used only for exploration

# Display updated missing values summary
print("\nMissing Values Summary (After Cleaning):")
print(missing_values_table(data))

# Verify critical columns
print("\nData Preview (Key Columns):")
print(data[['Industry', 'Sector', 'Size', 'Rating', 'Min_Salary', 'Max_Salary', 'Location', 'Job Title', 'Revenue']].head())

# Drop unnamed columns
data = data.loc[:, ~data.columns.str.contains('^_')]

# Verify remaining columns
print(data.columns)

# Histogram for Max Salary
plt.figure(figsize=(10, 6))
sns.histplot(data['Max_Salary'], bins=30, kde=True, color='red')
plt.title("Distribution of Maximum Salaries", fontsize=16)
plt.xlabel("Max Salary ($)", fontsize=14)
plt.ylabel("Frequency", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.show()

# Histogram for Min Salary
plt.figure(figsize=(10, 6))
sns.histplot(data['Min_Salary'], bins=30, kde=True, color='blue')
plt.title("Distribution of Minimum Salaries", fontsize=16)
plt.xlabel("Min Salary ($)", fontsize=14)
plt.ylabel("Frequency", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.tight_layout()
plt.show()

# Group by 'Company Name' and count the number of job postings with 'Easy Apply' as True
df_easy_apply = data[data['Easy Apply'] == 1]
top_companies = df_easy_apply.groupby('Company Name')['Easy Apply'].count().reset_index()

# Sort companies by the number of postings and select the top 10
top_companies = top_companies.sort_values('Easy Apply', ascending=False).head(10)

# Bar plot for the top 10 companies
title_font_size = 16
axis_label_font_size = 12
tick_label_font_size = 11
x_label_rotation = 45

plt.figure(figsize=(10, 5))
sns.barplot(data=top_companies, x='Company Name', y='Easy Apply', palette='Set1')

plt.title("Top 10 Companies Hiring for Data Analyst Roles Easily\n", fontsize=title_font_size)
plt.xlabel("\nCompany Name", fontsize=axis_label_font_size)
plt.ylabel("Number of Easy Apply Openings\n", fontsize=axis_label_font_size)

# Customize x-axis tick labels
plt.xticks(rotation=x_label_rotation, ha='right', fontsize=tick_label_font_size)
plt.yticks(fontsize=tick_label_font_size)

plt.tight_layout()
plt.show()

# Group by 'Location' and calculate the mean of 'Min_Salary' and 'Max_Salary'
city_salary = data.groupby('Location')[['Min_Salary', 'Max_Salary']].mean().reset_index()

# Sort by 'Max_Salary' and select the top 20 cities
top_cities = city_salary.sort_values('Max_Salary', ascending=False).head(20)

# Create a bar plot for salary distribution
fig = plt.figure(figsize=(12, 6))
plt.bar(top_cities['Location'], top_cities['Max_Salary'] - top_cities['Min_Salary'],
        bottom=top_cities['Min_Salary'], label='Max Salary', alpha=0.7)
plt.bar(top_cities['Location'], top_cities['Min_Salary'], label='Min Salary', alpha=0.7)


plt.title("Top 20 Cities by Average Salaries", fontsize=16)
plt.xlabel("City", fontsize=12)
plt.ylabel("Salary ($)", fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=11)
plt.yticks(fontsize=10)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()

# Group by 'Job Title' and calculate the mean of 'Min_Salary' and 'Max_Salary'
role_salary = data.groupby('Job Title')[['Min_Salary', 'Max_Salary']].mean().reset_index()

# Sort by 'Max_Salary' and select the top 20 roles
top_roles = role_salary.sort_values('Max_Salary', ascending=False).head(20)

# Create a bar plot for salary distribution with dynamic y-axis scaling
fig, ax = plt.subplots(figsize=(14, 8))
bars_min = ax.bar(top_roles['Job Title'], top_roles['Min_Salary'], label='Min Salary', alpha=0.9)
bars_max = ax.bar(top_roles['Job Title'], top_roles['Max_Salary'] - top_roles['Min_Salary'],
                  bottom=top_roles['Min_Salary'], label='Max Salary', alpha=0.9)

# Adjust y-axis dynamically
ax.set_ylim(0, top_roles['Max_Salary'].max() * 1.1)

# Titles and labels
ax.set_title("Top 20 Roles by Average Salaries\n", fontsize=16)
ax.set_xlabel("\nJob Title", fontsize=12)
ax.set_ylabel("Salary ($)\n", fontsize=12)
ax.set_xticks(range(len(top_roles['Job Title'])))
ax.set_xticklabels(top_roles['Job Title'], rotation=45, ha='right', fontsize=10)
ax.tick_params(axis='y', labelsize=10)

# Add legend
ax.legend(fontsize=12)

# Tight layout
plt.tight_layout()
plt.show()

# Count the number of companies for each employee size category
size_distribution = data['Size'].value_counts().reset_index()
size_distribution.columns = ['Employee Size', 'Number of Companies']

# Calculate the maximum value for dynamic y-axis scaling
y_max = size_distribution['Number of Companies'].max()

# Bar plot with dynamic y-axis
plt.figure(figsize=(12, 6))
sns.barplot(
    data=size_distribution,
    x='Employee Size',
    y='Number of Companies',
    palette='coolwarm',
    dodge=False
)

# Adjust y-axis dynamically
plt.ylim(0, y_max * 1.1)  # Add a 10% buffer above the max value

# Titles and labels
plt.title("Number of Companies by Employee Size\n", fontsize=16)
plt.xlabel("\nEmployee Size", fontsize=12)
plt.ylabel("Number of Companies\n", fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(fontsize=10)

plt.tight_layout()
plt.show()

# Function to convert revenue ranges to numeric values (in millions)
def convert_revenue_to_numeric(revenue):
    if pd.isnull(revenue) or revenue in ["Unknown / Non-Applicable", "-1"]:
        return None
    revenue = revenue.replace("(USD)", "").replace("$", "").strip()
    if "million" in revenue:
        if "Less than" in revenue:
            return 0.5  # Assume less than $1 million is 0.5 million
        revenue_range = revenue.replace("million", "").split("to")
        try:
            return float(revenue_range[-1].replace("+", "").strip())
        except ValueError:
            return None  # Handle unexpected strings gracefully
    if "billion" in revenue:
        revenue_range = revenue.replace("billion", "").split("to")
        try:
            return float(revenue_range[-1].replace("+", "").strip()) * 1000
        except ValueError:
            return None  # Handle unexpected strings gracefully
    return None

# Apply the updated cleaning function to the 'Revenue' column
data['Cleaned_Revenue'] = data['Revenue'].apply(convert_revenue_to_numeric)

# Verify the cleaned revenue column
print(data[['Revenue', 'Cleaned_Revenue']].head())

# Calculate the average revenue for each sector
sector_revenue = data.groupby('Sector')['Cleaned_Revenue'].mean().reset_index()
sector_revenue = sector_revenue.sort_values('Cleaned_Revenue', ascending=False).head(20)

# Bar plot for revenue by sector
plt.figure(figsize=(12, 6))
sns.barplot(data=sector_revenue, x='Sector', y='Cleaned_Revenue', palette='flare')

y_max = sector_revenue['Cleaned_Revenue'].max()
plt.ylim(0, y_max * 1.1)

# Titles and labels
plt.title("Revenue by Sector", fontsize=16)
plt.xlabel("\nSector", fontsize=12)
plt.ylabel("Average Revenue (in Million USD)\n", fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(fontsize=10)

plt.tight_layout()
plt.show()

import re

# Preprocess job titles
data['Job Title'] = data['Job Title'].str.replace(r'\bSr\b', 'Senior', regex=True)
data['Job Title'] = data['Job Title'].str.replace(r'\bJr\b', 'Junior', regex=True)
data['Job Title'] = data['Job Title'].str.replace(r'\bAVP\b', 'Assistant Vice President', regex=True)

# Clean job titles
def clean_job_title(title):
    title = re.split(r'[-/]', title)[0]
    return title.lower().strip()

data['Job Title'] = data['Job Title'].fillna("")
job_titles_cleaned = data['Job Title'].apply(clean_job_title)

# Join all cleaned job titles into a single string
word_cloud_text = " ".join(job_titles_cleaned)

# Generate the word cloud
wordcloud = WordCloud(
    width=800,
    height=400,
    colormap='viridis',
    background_color='white',
    max_words=100
).generate(word_cloud_text)

# Display the word cloud
plt.figure(figsize=(14, 7))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Top Words in Job Titles", fontsize=18)
plt.tight_layout()
plt.show()

# Group by 'Rating' and count the number of companies for each rating
rating_distribution = data.groupby('Rating')['Company Name'].count().reset_index()
rating_distribution.columns = ['Rating', 'Count']

# Sort ratings in descending order and select the top 20
top_ratings = rating_distribution.sort_values('Count', ascending=False).head(20)

# Bar plot for company ratings
plt.figure(figsize=(12, 6))
sns.barplot(
    data=top_ratings,
    x='Rating',
    y='Count',
    hue='Rating',
    palette='flare',
    dodge=False,
    legend=False  # Suppress the legend
)

# Adjust y-axis dynamically
y_max = top_ratings['Count'].max()
plt.ylim(0, y_max * 1.1)

# Titles and labels
plt.title("Top 20 Company Ratings\n", fontsize=16)
plt.xlabel("\nRating", fontsize=12)
plt.ylabel("Number of Companies\n", fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(fontsize=10)

plt.tight_layout()
plt.show()

# Group by 'Sector' and calculate the average minimum and maximum salaries
sector_salary = data.groupby('Sector')[['Min_Salary', 'Max_Salary']].mean().reset_index()
sector_salary = sector_salary.rename(columns={'Min_Salary': 'Avg_Min_Salary', 'Max_Salary': 'Avg_Max_Salary'})

# Sort sectors by the average maximum salary and select the top 20
top_sectors = sector_salary.sort_values('Avg_Max_Salary', ascending=False).head(20)

# Bar plot for average salaries by sector
title_font_size = 16
axis_label_font_size = 12
tick_label_font_size = 11
x_label_rotation = 45

plt.figure(figsize=(14, 8))
plt.bar(top_sectors['Sector'], top_sectors['Avg_Min_Salary'], label='Avg Min Salary', alpha=0.7, color='blue')
plt.bar(
    top_sectors['Sector'],
    top_sectors['Avg_Max_Salary'] - top_sectors['Avg_Min_Salary'],
    bottom=top_sectors['Avg_Min_Salary'],
    label='Avg Max Salary',
    alpha=0.7,
    color='red'
)

# Adjust y-axis dynamically
y_max = top_sectors['Avg_Max_Salary'].max()
plt.ylim(0, y_max * 1.1)

# Titles and labels
plt.title("Sectors with Average Minimum and Maximum Salaries\n", fontsize=title_font_size)
plt.xlabel("\nSector", fontsize=axis_label_font_size)
plt.ylabel("Salary ($)", fontsize=axis_label_font_size)
plt.xticks(rotation=x_label_rotation, ha='right', fontsize=tick_label_font_size)
plt.yticks(fontsize=tick_label_font_size)
plt.legend(fontsize=12)

plt.tight_layout()
plt.show()

# Calculate salary growth potential for each sector
sector_salary = data.groupby('Sector')[['Min_Salary', 'Max_Salary']].mean().reset_index()
sector_salary['Salary_Range'] = sector_salary['Max_Salary'] - sector_salary['Min_Salary']

# Sort sectors by salary growth potential
top_sectors = sector_salary.sort_values('Salary_Range', ascending=False)

# Bar plot for salary growth potential by sector
title_font_size = 16
axis_label_font_size = 12
tick_label_font_size = 11
x_label_rotation = 45

plt.figure(figsize=(14, 6))
sns.barplot(data=top_sectors, x='Sector', y='Salary_Range', palette='crest')

# Adjust y-axis dynamically
y_max = top_sectors['Salary_Range'].max()
plt.ylim(0, y_max * 1.2)

# Titles and labels
plt.title("Salary Growth Potential by Sector\n", fontsize=title_font_size)
plt.xlabel("\nSector", fontsize=axis_label_font_size)
plt.ylabel("Salary Growth Potential ($)\n", fontsize=axis_label_font_size)
plt.xticks(rotation=x_label_rotation, ha='right', fontsize=tick_label_font_size)
plt.yticks(fontsize=tick_label_font_size)

plt.tight_layout()
plt.show()

# Count the number of openings for each location
location_openings = data['Location'].value_counts().reset_index()
location_openings.columns = ['Location', 'No_of_Openings']

# Select the top 10 locations with the highest openings
top_locations = location_openings.head(10)

# Bar plot for the top 10 locations with job openings
plt.figure(figsize=(14, 7))  # Updated size for clarity
sns.barplot(data=top_locations, x='Location', y='No_of_Openings', palette='crest')

# Titles and labels
plt.title("Top 10 Locations for Data Analyst Roles\n", fontsize=16)  # Larger font size for the title
plt.xlabel("\nLocation", fontsize=14)  # Updated for axis label consistency
plt.ylabel("Number of Openings\n", fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=12)  # Adjusted font size and alignment
plt.yticks(fontsize=12)

plt.tight_layout()
plt.show()

# Group by 'Size' and calculate the average revenue
size_revenue = data.groupby('Size')['Cleaned_Revenue'].mean().reset_index()
size_revenue = size_revenue.rename(columns={'Cleaned_Revenue': 'Avg_Revenue'})

# Sort by company size for logical order
size_revenue = size_revenue.sort_values('Avg_Revenue', ascending=False)

# Bar plot for revenue by company size
plt.figure(figsize=(14, 7))
barplot = sns.barplot(data=size_revenue, x='Size', y='Avg_Revenue', palette='rocket')

# Adjust y-axis dynamically
y_max = size_revenue['Avg_Revenue'].max()
plt.ylim(0, y_max * 1.1)

# Annotate exact values on top of each bar
for bar in barplot.patches:
    bar_height = bar.get_height()
    barplot.annotate(
        f'{bar_height:.1f}',  # Format to one decimal place
        (bar.get_x() + bar.get_width() / 2, bar_height),  # Position on top of the bar
        ha='center',  # Center alignment
        va='bottom',  # Position above the bar
        fontsize=12  # Font size for annotation
    )

# Titles and labels
plt.title("Average Revenue by Company Size\n", fontsize=16)
plt.xlabel("\nCompany Size", fontsize=14)
plt.ylabel("Average Revenue (in Million USD)\n", fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=12)
plt.yticks(fontsize=12)

plt.tight_layout()
plt.show()

# Count the number of positions for each sector
sector_positions = data['Sector'].value_counts().reset_index()
sector_positions.columns = ['Sector', 'No_of_Positions']

# Select the top 10 sectors with the highest positions
top_sectors_positions = sector_positions.head(10)

# Bar plot for the top 10 sectors with job positions
plt.figure(figsize=(14, 7))
sns.barplot(data=top_sectors_positions, x='Sector', y='No_of_Positions', palette='mako')


# Titles and labels
plt.title("Top 10 Sectors with Job Positions\n", fontsize=16)
plt.xlabel("\nSector", fontsize=14)
plt.ylabel("Number of Positions\n", fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=12)
plt.yticks(fontsize=12)

plt.tight_layout()
plt.show()

# Count the number of positions for each location
location_positions = data['Location'].value_counts().reset_index()
location_positions.columns = ['Location', 'No_of_Positions']

# Select the top 10 locations with the highest number of positions
top_locations_positions = location_positions.head(10)

# Bar plot for the top 10 locations with job positions
title_font_size = 16
axis_label_font_size = 12
tick_label_font_size = 11
x_label_rotation = 45

plt.figure(figsize=(12, 6))
sns.barplot(
    data=top_locations_positions,
    x='Location',
    y='No_of_Positions',
    hue='Location',  # Assign `x` to `hue`
    palette='coolwarm',
    dodge=False,
    legend=False  # Suppress legend
)

# Adjust y-axis dynamically
y_max = top_locations_positions['No_of_Positions'].max()
plt.ylim(0, y_max * 1.1)

# Titles and labels
plt.title("Top 10 Locations with Job Positions", fontsize=title_font_size)
plt.xlabel("Location", fontsize=axis_label_font_size)
plt.ylabel("Number of Positions", fontsize=axis_label_font_size)
plt.xticks(rotation=x_label_rotation, ha='right', fontsize=tick_label_font_size)
plt.yticks(fontsize=tick_label_font_size)

plt.tight_layout()
plt.show()

import pandas as pd
import plotly.graph_objects as go

# Ensure the 'Location' column exists and process it to extract state abbreviations
if 'Location' in data.columns:
    # Extract state abbreviations from the 'Location' column
    state_positions = data['Location'].str.extract(r',\s*(\w{2})$', expand=False)

    # Check for any NaN values (locations without valid states) and drop them
    state_positions = state_positions.dropna()

    # Count the number of job postings by state
    state_positions = state_positions.value_counts().reset_index()
    state_positions.columns = ['State', 'No_of_Positions']

    # Create the choropleth map for Job Intensity
    fig_jobs = go.Figure(data=go.Choropleth(
        locations=state_positions['State'],  # State abbreviations
        z=state_positions['No_of_Positions'],  # Intensity of job postings
        locationmode='USA-states',
        colorscale='YlOrRd',  # Bright-to-dark color scale
        colorbar_title="Job Count",
        text=state_positions['State'],  # State abbreviation
    ))

    # Add state labels (abbreviations inside their territories) without legend
    for i, row in state_positions.iterrows():
        fig_jobs.add_trace(go.Scattergeo(
            locationmode='USA-states',
            locations=[row['State']],
            text=row['State'],  # Add state abbreviation
            mode='text',
            textfont=dict(color='black', size=10),  # Customize font size and color
            showlegend=False  # Hide these traces from the legend
        ))

    # Update map layout with centered title and font size options
    fig_jobs.update_layout(
        title={
            'text': "Job Intensity by State",
            'x': 0.5,  # Center the title
            'xanchor': 'center',
            'font': {'size': 26}  # Title font size
        },
        geo=dict(
            scope='usa',
            showlakes=True,
            lakecolor="lightblue",
            showcoastlines=True,
            coastlinecolor="gray",
            showland=True,
            landcolor="lightgray",
            projection_type='albers usa',  # Projection for USA map
        ),
        font=dict(size=14),  # Overall font size for components
        width=900,  # Set figure width
        height=500,  # Set figure height
    )

    # Show the updated map
    fig_jobs.show()
else:
    print("The 'Location' column is missing from the dataset. Please check the input data.")

import pandas as pd
import plotly.graph_objects as go

# Ensure the 'State' column is extracted and added to the main DataFrame
data['State'] = data['Location'].str.extract(r',\s*(\w{2})$', expand=False)

# Ensure there are no NaN states
data = data.dropna(subset=['State'])

# Convert Min_Salary to numeric if it's not already
if 'Min_Salary' in data.columns:
    data['Min_Salary'] = pd.to_numeric(data['Min_Salary'], errors='coerce')

    # Group by 'State' and calculate the average minimum salary
    state_min_salary = data.groupby('State')['Min_Salary'].mean().reset_index()
    state_min_salary.columns = ['State', 'Avg_Min_Salary']

    # Create the choropleth map for Average Minimum Salary
    fig_min_salary = go.Figure(data=go.Choropleth(
        locations=state_min_salary['State'],  # State abbreviations
        z=state_min_salary['Avg_Min_Salary'],  # Average minimum salary
        locationmode='USA-states',
        colorscale='YlOrRd',  # Original file color scale
        colorbar_title="Avg Min Salary",
        text=state_min_salary['State'],  # State abbreviation for hover
    ))

    # Add state labels without legend
    for i, row in state_min_salary.iterrows():
        fig_min_salary.add_trace(go.Scattergeo(
            locationmode='USA-states',
            locations=[row['State']],
            text=row['State'],  # Add state abbreviation
            mode='text',
            textfont=dict(color='black', size=10),  # Original font size for state labels
            showlegend=False  # Suppress legend
        ))

    # Update layout settings
    fig_min_salary.update_layout(
        title={
            'text': "Average Minimum Salary by State",
            'x': 0.5,  # Centered title
            'xanchor': 'center',
            'font': {'size': 26}  # Title font size matches original
        },
        geo=dict(
            scope='usa',
            showlakes=True,
            lakecolor="lightblue",  # Original settings for lakes
            showcoastlines=True,
            coastlinecolor="gray",
            showland=True,
            landcolor="lightgray",
            projection_type='albers usa'  # Aligned projection type
        ),
        font=dict(size=14),  # Component font size matches original
        width=900,  # Original width
        height=500,  # Original height
    )

    # Show the map
    fig_min_salary.show()
else:
    print("The 'Min_Salary' column is missing from the dataset. Please check your data.")

from matplotlib import cm

# Group by 'State' and sum up the revenue
state_revenue = data.groupby('State')['Cleaned_Revenue'].sum().reset_index()
state_revenue.columns = ['State', 'Total_Revenue']

# Remove states with no revenue data (NaN or zero)
state_revenue = state_revenue.dropna(subset=['Total_Revenue'])
state_revenue = state_revenue[state_revenue['Total_Revenue'] > 0]

# Calculate total revenue for percentage calculation
total_revenue = state_revenue['Total_Revenue'].sum()

# Identify states with less than 1% contribution and combine them into "Other States"
state_revenue['Percentage'] = (state_revenue['Total_Revenue'] / total_revenue) * 100
other_states = state_revenue[state_revenue['Percentage'] < 1]['Total_Revenue'].sum()
state_revenue = state_revenue[state_revenue['Percentage'] >= 1]

# Add "Other States" row
state_revenue = pd.concat([state_revenue, pd.DataFrame([{'State': 'Other States', 'Total_Revenue': other_states}])])

# Recalculate percentages after combining
state_revenue['Percentage'] = (state_revenue['Total_Revenue'] / state_revenue['Total_Revenue'].sum()) * 100

# Assign unique colors for each state
colors = plt.cm.tab20.colors[:len(state_revenue)]  # Generate unique colors based on the number of slices

# Set adjustable font size for percentage annotations
percentage_font_size = 8  # You can adjust this value

# Plot the pie chart with dynamic rotation
plt.figure(figsize=(12, 8))
wedges, texts, autotexts = plt.pie(
    state_revenue['Total_Revenue'],
    labels=None,  # Omit labels on slices (handled in the legend)
    autopct='%1.1f%%',  # Annotate the slices with percentage shares
    startangle=140,
    colors=colors,
    rotatelabels=True  # Enable dynamic rotation of text
)

# Adjust font size for percentages
for autotext in autotexts:
    autotext.set_fontsize(percentage_font_size)

# Add a legend for the states
plt.legend(
    loc='upper left',
    labels=state_revenue['State'],  # Assign state names to the legend
    title="States",
    title_fontsize=12,
    fontsize=10,
    bbox_to_anchor=(1, 0.5),  # Position the legend to the right of the plot
    frameon=True  # Add a frame around the legend
)

# Title for the plot
plt.title("State-wise Revenue Share", fontsize=16)

# Adjust layout for better spacing
plt.tight_layout()
plt.show()

# Step 1: Calculate Job Count per State
job_count = data['Location'].apply(lambda x: x.split(',')[-1].strip()).value_counts().reset_index()
job_count.columns = ['State', 'Job_Count']

# Step 2: Calculate Easy Apply Count per State
easy_apply_count = data.groupby(data['Location'].apply(lambda x: x.split(',')[-1].strip()))['Easy Apply'].sum().reset_index()
easy_apply_count.columns = ['State', 'Easy_Apply_Count']

# Step 3: Calculate Average Minimum Salary per State
state_avg_min_salary = data.groupby(data['Location'].apply(lambda x: x.split(',')[-1].strip()))['Min_Salary'].mean().reset_index()
state_avg_min_salary.columns = ['State', 'Avg_Min_Salary']

# Step 4: Merge all metrics
state_interest = pd.merge(job_count, easy_apply_count, on='State', how='inner')
state_interest = pd.merge(state_interest, state_avg_min_salary, on='State', how='inner')

# Step 5: Normalize the metrics
state_interest['Normalized_Job_Count'] = state_interest['Job_Count'] / state_interest['Job_Count'].max()
state_interest['Normalized_Easy_Apply_Count'] = state_interest['Easy_Apply_Count'] / state_interest['Easy_Apply_Count'].max()
state_interest['Normalized_Avg_Min_Salary'] = state_interest['Avg_Min_Salary'] / state_interest['Avg_Min_Salary'].max()

# Step 6: Calculate Interest Rate
state_interest['Interest_Rate'] = (
    state_interest['Normalized_Job_Count'] *
    state_interest['Normalized_Easy_Apply_Count'] *
    state_interest['Normalized_Avg_Min_Salary']
)

# Step 7: Select the Top 5 States with the Highest Interest Rates
top_states_interest = state_interest.nlargest(5, 'Interest_Rate')

fig_interest_rate = px.bar(
    top_states_interest,
    x='State',
    y='Interest_Rate',
    text='Interest_Rate',
    title='Top 5 States by Interest Rate',
    labels={'Interest_Rate': 'Interest Rate', 'State': 'State'},
    color='Interest_Rate',
    color_continuous_scale='Bluered'
)

# Customize the layout for better readability
fig_interest_rate.update_traces(
    texttemplate='%{text:.4f}',  # Show interest rate with 4 decimal points
    textposition='outside'
)
fig_interest_rate.update_layout(
    title={'x': 0.5, 'xanchor': 'center', 'font': {'size': 24}},  # Center the title
    xaxis_title='State',
    yaxis_title='Interest Rate',
    font=dict(size=14),
    showlegend=False,
    width=900,  # Set figure width
    height=600   # Set figure height
)

# Show the bar chart
fig_interest_rate.show()

# Parse minimum and maximum salaries from 'Salary Estimate'
data['Min_Salary'] = data['Min_Salary'].fillna(0)
data['Max_Salary'] = data['Max_Salary'].fillna(0)

# Calculate the average salary for each company
data['Avg_Salary'] = (data['Min_Salary'] + data['Max_Salary']) / 2

# Group by 'Sector' to calculate the sector average salary
sector_avg_salary = data.groupby('Sector')['Avg_Salary'].mean().reset_index()
sector_avg_salary.columns = ['Sector', 'Sector_Avg_Salary']

# Merge sector average salary back into the main dataset
data = pd.merge(data, sector_avg_salary, on='Sector', how='left')

# Calculate Fairness Rate for each company
data['Fairness_Rate'] = data['Avg_Salary'] / data['Sector_Avg_Salary']

# Select the top 10 companies with the highest fairness rate
top_high_fairness = data.nlargest(10, 'Fairness_Rate')[['Company Name', 'Sector', 'Fairness_Rate']]

# Redefine the highest fairness rate data
highest_fairness = data.nlargest(10, 'Fairness_Rate')[['Company Name', 'Sector', 'Fairness_Rate']]

# Bar Chart for Top 10 Companies with Highest Fairness Rate
import plotly.express as px

fig_high = px.bar(
    highest_fairness,
    x='Company Name',
    y='Fairness_Rate',
    title='Top 10 Companies with the Highest Fairness Rate',
    labels={'Fairness_Rate': 'Fairness Rate', 'Company Name': 'Company'},
    text='Fairness_Rate',
    color_discrete_sequence=['#1f77b4']  # Fixed blue color
)

# Update traces for thinner bars and precise annotations
fig_high.update_traces(
    texttemplate='%{text:.4f}',  # Show fairness rate with 4 decimal places
    textposition='outside',
    width=0.8  # Thinner bars
)

# Customize layout for readability
fig_high.update_layout(
    title={
        'text': 'Top 10 Companies with the Highest Fairness Rate',
        'x': 0.5,  # Center the title
        'font': {'size': 24}  # Larger font size for the title
    },
    xaxis=dict(
        title='Company',
        tickangle=45  # Rotate x-axis labels
    ),
    yaxis=dict(
        title='Fairness Rate',
        range=[highest_fairness['Fairness_Rate'].min() * 0.9, highest_fairness['Fairness_Rate'].max() * 1.1]  # Dynamic y-axis
    ),
    font=dict(size=15),  # General font size for the chart
    showlegend=False,  # No legend needed
    width=900,  # Set figure width
    height=600   # Set figure height
)

# Show the bar chart
fig_high.show()

# Select the top 10 companies with the lowest fairness rate
lowest_fairness = data.nsmallest(10, 'Fairness_Rate')[['Company Name', 'Sector', 'Fairness_Rate']]

# Bar Chart for Top 10 Companies with Lowest Fairness Rate
fig_low = px.bar(
    lowest_fairness,
    x='Company Name',
    y='Fairness_Rate',
    title='Top 10 Companies with the Lowest Fairness Rate',
    labels={'Fairness_Rate': 'Fairness Rate', 'Company Name': 'Company'},
    text='Fairness_Rate',
    color_discrete_sequence=['#d62728']  # Fixed red color
)

# Update traces for precise annotations and thinner bars
fig_low.update_traces(
    texttemplate='%{text:.4f}',  # Show fairness rate with 4 decimal places
    textposition='outside',
    width=0.8  # Thinner bars
)

# Customize layout for readability
fig_low.update_layout(
    title={
        'text': 'Top 10 Companies with the Lowest Fairness Rate',
        'x': 0.5,  # Center the title
        'font': {'size': 24}  # Larger font size for the title
    },
    xaxis=dict(
        title='Company',
        tickangle=45  # Rotate x-axis labels
    ),
    yaxis=dict(
        title='Fairness Rate',
        range=[lowest_fairness['Fairness_Rate'].min() * 0.9, lowest_fairness['Fairness_Rate'].max() * 1.1]  # Dynamic y-axis
    ),
    font=dict(size=15),  # General font size for the chart
    showlegend=False,  # No legend needed
    width=900,  # Set figure width
    height=600   # Set figure height
)

# Show the bar chart
fig_low.show()

data['Sector_Avg_Salary'] = data['Sector_Avg_Salary'].fillna(0)  # Or another default value

data['Fairness_Rate'] = data['Avg_Salary'] / data['Sector_Avg_Salary']

import plotly.express as px

# Scatter plot with Black-to-Orange colormap and rescaled axes
fig_scatter = px.scatter(
    data,
    x='Sector_Avg_Salary',
    y='Avg_Salary',
    color='Fairness_Rate',
    title='Average Salary vs Sector Average Salary by Fairness Rate',
    labels={'Sector_Avg_Salary': 'Sector Average Salary', 'Avg_Salary': 'Company Average Salary'},
    color_continuous_scale=['orange', 'black'],  # Black-to-Orange colormap
    hover_data=['Company Name', 'Sector']
)

# Add diagonal line (y = x) to represent fairness parity
max_salary = max(data['Sector_Avg_Salary'].max(), data['Avg_Salary'].max())
fig_scatter.add_shape(
    type="line",
    x0=0,
    y0=0,
    x1=max_salary,
    y1=max_salary,
    line=dict(color="black", width=2, dash="dash"),
)

# Rescale axes for better spread visualization
fig_scatter.update_layout(
    title={'x': 0.5, 'font': {'size': 24}},
    xaxis_title='Sector Average Salary',
    yaxis_title='Company Average Salary',
    font=dict(size=14),
    width=1000,  # Increased width
    height=1000,  # Increased height
    xaxis=dict(range=[0, max_salary * 1.1]),  # Extend x-axis range
    yaxis=dict(range=[0, max_salary * 1.1])   # Extend y-axis range
)

# Show the scatter plot
fig_scatter.show()